### ISSUE TITLE
include N glint errors caught in report summary

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#1105]
Currently we do not include caught glint errors in the summary report of `rehearsal fix`:

## CURRENT
```
✔ Initialize
✔ Analyzing project dependency graph ...
✔ Types Inferred
  9 errors caught by rehearsal
  1 have been fixed by rehearsal
  8 errors need to be fixed manually
  -- 4 ts errors, marked by @ts-expect-error @rehearsal TODO
  -- 4 eslint errors, with details in the report
```

## PROPOSED
```
✔ Initialize
✔ Analyzing project dependency graph ...
✔ Types Inferred
  13 errors caught by rehearsal
  1 have been fixed by rehearsal
  12 errors need to be fixed manually
  -- 4 ts errors, marked by @ts-expect-error @rehearsal TODO
  -- 4 glint errors, marked by @glint-expect-error @rehearsal TODO
  -- 4 eslint errors, with details in the report
```

**Comment by wondersloth** [comment]
Investigate this.

We currently count errors in the report plugin by counting the `@glint-expect-errors' in a file.

Currently we write errors to hbs files, but it produces invalid syntax because we inject errors in an invalid region in the hbs.

We can inject errors in a valid region if we parse the hbs and inject in a safe place, but there is a downside. The downside being these injected `@glint-expect-errror` directives will not all be suppress  glint from reporting the error.

So we can show the total errors, add a comment, but cannot suppress all possible glint errors in an hbs context due to https://github.com/typed-ember/glint/issues/589

**Comment by wondersloth** [comment]
We would need to refactor the glintcomment pluing to do something more like:
https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/plugins/src/plugins/lint.plugin.ts
