### ISSUE TITLE
Add `experimentalDecorators=true` to default tsconfig.json

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#510]
**Problem**
If a source file in a project is using decorators.

```
class SomeClass {
  @tracked someProperty = 'Hello';
}
```

The first ts-ignore comment is added saying:

```
/* @ts-expect-error @rehearsal TODO TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning. */
@tracked someProperty = 'Hello';
```
**Fix**
Short term add `experimentalDecroators: true` to tsconfig.json so we can annotate types by default. This way we can add a type to the decorated value.

Conditionally add `experimentalDecorators: true` to `tsconfig.json` if we detect usage of decorators.

Conditions for usage:
- Source contains usage of `@something foo;`
- Found dependency for `@babel/plugin-proposal-decorators`
- Found babel plugin usage of:
  ```
  ['@babel/plugin-proposal-decorators', { legacy: true }],
  ```

**Comment by egorio** [comment]
This can be implemented as CodeFix for TS1219.

**Comment by egorio** [comment]
TS already has a codefix for it `enableExperimentalDecorators` , but not sure how this works. 
Need to check.

**Comment by brendaHuang** [comment]
Starting from TypeScript 5.0-beta, decorators will be valid syntax even without the '--experimentalDecorators' flag. [See release notes for TypeScript 5.0-beta](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/). 5.0 will be stable release around end of March. 

Error TS1219 that requires the adding of `'experimentalDecorators': true` to tsconfig.json has been retired from the diagnostic message list. The code fix to insert the flag has been deprecated as well.

If we add the flag or apply the codefix, 

- Pros: Users of ts 4.9 or below will have to manually fix the error
- Cons: Complexity of Rehearsal code will increase. 

Since the error is not fatal, I am leaning toward doing nothing for TS1219.

**Comment by lynchbomb** [comment]
Since this is going to be baked into the default for TS within the next ~3 weeks we can close this issue
