### ISSUE TITLE
SARIF Report Points To Incorrect Information

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#536]
We really need to make sure that the produced reports accurately point to the parts of the code that need to be modified. Currently the report is not useful because it points to random ranges in lines.

<img width="1589" alt="Screen Shot 2022-12-15 at 10 46 33 PM" src="https://user-images.githubusercontent.com/183799/208017609-f9e5cfa0-8fbc-40c1-9af1-53a2a703aa29.png">

**Comment by aviheidir** [comment]
Is this related to (regression caused by) the fix for issue #497?

**Comment by brendaHuang** [comment]
@aviheidir No. I checked out the repo before solution to issue #497, the same issues already existed. These errors mainly have to do with JSDoc. I will look into it.

**Comment by egorio** [comment]
@chadhietala @brendaHuang I don't think it's possible to get the correct line numbers because of:

- we apply changes from the bottom top, so after we fix something above the previous fix, this action invalidates start position of the previous fix

- after we changed the diagnostics order this became even worst

- plus we run lint after all fixes are applied and it can change inserted code as well which can change both start and end positions.

I thought about something to track all offsets (like a changes tracker) or try to find the right positions of inserted (not sure about removed) texts after we applied all changes in the file by searching for inserted code in the file...

**Comment by egorio** [comment]
After discussion:

- Exit diagnostics
- Run the Lint plugin
- Run new plugin ChangesTracker (TodoChecker).
- For now, only reports unfixed errors (@rehearsal comments)?

**Comment by brendaHuang** [comment]
From the run of the initial diagnostic plugin, we'll apply the fixes and report the count of fixes that have been applied and the count of issues that need to be fixed manually. (For the ones that have been fixed, code author can get the diff through git.)

From the run of the final ToDoTracker, we will report the line and column numbers of those that still need to be fixed.

**Comment by egorio** [comment]
Just in case, for fixed we can also add a description (`fix.description`) on the action that was applied, https://github.com/rehearsal-js/rehearsal-js/issues/525

**Comment by brendaHuang** [comment]
In the case of the file in the screen shot, removing lint plugins from migrate produces the same result: reporting still points to the exactly wrong file. It's the code fixes that cause the misalignment in this file, when a code fix that has multiple lines is added, the calculation of line numbers gets chaotic. In the screenshot attached here, Line 50 - Line 57 is inserted by code fix, and that causes the location of the next diagnostic to be off by 5 lines.
![Screenshot 2022-12-18 at 9 55 22 AM](https://user-images.githubusercontent.com/26440597/208312088-49b5bd2c-86f0-4a59-a418-50a9005c46a3.png)
