### ISSUE TITLE
Package selections in non-interactive mode

### ISSUE THREAD

**Issue by haochuan** [rehearsal-js/rehearsal-js#576]
Currently in interactive mode we are doing two things:
1. Let user select child package to run partial migration (if there is any)
2. Go through migrated files one by one and ask for actions (accept/edit/discard)

I feel it makes more sense to also enable No.1 in non-interactive mode, and No.2 is the only difference between interactive and normal mode.

@chadhietala @lynchbomb Any idea/thought on this one?

**Comment by lynchbomb** [comment]
This is a UX flow - we should likely wait until we get feedback from early adopters and implement if necessary.

**Comment by egorio** [comment]
I think e can provide a command to display a tree (graph) of files from any --entrypoing that can be migrated (including separation by package names). 

Then allow the user to narrow the migration scope based on the tree (use more narrow --entrypoint for instance)

Finally allow selecting list of files to be migrated under --entrypoint at one run.

Users can separate what to migrate by chanks because they usually knows app more :)

**Comment by lynchbomb** [comment]
In this more involved interactive mode lets possibly re-expose behind a flag this time, the ability for rehearsal to control creating commits on `migrate` command interactive mode (we allow this for upgrade)

**Comment by lynchbomb** [comment]
Circling back on this. We definitely need to be able to migrate a child package (app/add on) in non-interactive mode (—-ci). However we do not want prompts in this mode.
