### ISSUE TITLE
Refactor blocking code from all plugins

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#630]
Similar to what we are doing in [migrate.ts](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/migrate/src/migrate.ts#L124-L214) we should refactor the blocking code in all plugins eg. [here](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/plugins/src/plugins/diagnostic-check.plugin.ts#L28), [here](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/plugins/src/plugins/diagnostic-fix.plugin.ts#L38) etc. as pull based with a generator/iterator implementation. 

This will likely be critical for the state management of the migrate command. Currently with the migrate command if you control-c from interactive mode all state is lost as we dont currently yield to saving the migrated files to disk. 

In the proposed refactor we could do just this; yield -> save to disk

- [ ] refactor and remove the `while` loops from all plugins

**Comment by egorio** [comment]
We have to use while loop in `-fix` plugins because each fix has side-effect on the file and program - fixing one issue can fix many others in this file or can bring new errors. We need to check the latest issues every time we modify file. 

We can think about removing the loop from `-check` (report) plugin where we just add comments (we can just add comments from the bottom top)... but will think.

I don't think while loop is causing the huge slowdown, but something inside (like [this](https://github.com/rehearsal-js/rehearsal-js/issues/890)) does it.
