### ISSUE TITLE
migrate CLI error out for eslint plugins when running migrate with -p option

### ISSUE THREAD

**Issue by haochuan** [rehearsal-js/rehearsal-js#663]
Existed `.eslintrc.js`:

```
module.exports = {
  ...
  plugins: ['ember'],
  ...
};
```

Run `rehearsal migrate`, we have:

```
› <project-path>/.eslintrc.js already exists, extending Rehearsal default typescript-related config
✖ Update eslintrc.js: Failed to load plugin 'ember' declared in '.eslintrc.js': Package subpath './lib/util/traverser' is not defined by "exports" in <project-path>/node_modules/eslint/package.json
Referenced from: <project-path>/.eslintrc.js
error:   Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin 'ember' declared in '.eslintrc.js': Package subpath './lib/util/traverser' is not defined by "exports" in <project-path>/node_modules/eslint/package.json
Referenced from: <project-path>/.eslintrc.js
```

**Comment by brendaHuang** [comment]
I also ran into the same issue. 

The culprit is [this line](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/config-lint.ts#L64):

By using `require`, we will able to retrieve .eslintrc.js if we run the `migrate` command in the target project. But require will fail, if we run the `migrate` command in a different directory by specifying -p.  

I tried to find a way to read .eslintrc.js and then parse it, and I am still looking.
