### ISSUE TITLE
Sequential Runs Overwrite existing SARIF files

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#693]
If you target only certain directories of a project for migration e.g.`rehearsal migrate -e foo` then `rehearsal migrate -e bar` you will overwrite the migration report. I think there are several paths forward that need to be discussed.

- Ask if we should overwrite the file
- Append into the file
- Write another file one already exists

**Comment by lynchbomb** [comment]
I think we should append into the file if one exists. For robust apps we can organize/filter the migration sonar report based on the file path and tagging.

**Comment by brendaHuang** [comment]
@chadhietala @lynchbomb 
Three scenarios of sequential runs:

1. Separate runs on different directories to get a full scan of the entire project. User needs to pass a flag so that we will append the reports for the repeated runs such as '--report-concat'
2. Repeated runs on the same directory. Each run will generate a refreshed report. Or user and run `--regen` flag. 
3. Repeated runs overlapping directories. For example, first time running in directory A that has subdirectories B and C, but second time running in subdirectory B. In this case we don't have necessary information to correctly merge reports. 

This ticket will only handle the first scenario.

**Comment by lynchbomb** [comment]
I actually think we should avoid a flag which handles something that should be foundational and **not** something like `--report-concat`. 

1. Separate runs append the report file by default. The report can contain an array of `migrations` which is an array of the existing reporting schema as a stack in the same file. 
2. Repeated runs on the same directory. Run `--regen`. Additionally can we match the `basePath` against the report. If its a match automatically run `--regen`. Since we know the user has already ran the report once on this basePath.
3. In this scenario if we append first and add a new validation/scrub function to the report which merges duplicate reporting for overlapping files with identical abs. paths into the `items` array. Then update timestamp, itemCount etc.

```
Run 1: DIR-A [b/foo.ts, b/blah.ts, c/blep.ts]

Run 2: DIR-B [foo.ts, blah.ts]

Run 3: DIR-C [blep.ts]
```

This would look something like:
```
// rehearsal-report.json
{
"migrations": [{"summary":"basePath":"DIR-A"},{"summary":"basePath":"DIR-B"},{"summary":"basePath":"DIR-C"}] etc.
}
```

**Comment by brendaHuang** [comment]
Good ideas. I will make the report json an array of migrations. 

My only concern is that if we automatically append to the existing report in the target project's root directory, that existing report may be obsolete. For example, the user may have made fixes between the runs. In that case, user knows whether if it makes sense to append or not and user needs to give us that signal, such as a prompt or a flag.

**Comment by lynchbomb** [comment]
In this instance if we were to run `--regen` wouldn't that update the report?

**Comment by brendaHuang** [comment]
Yes. Running --regen would refresh the report. But only user knows if he or she has just run --regen, so they still need to give us the signal. If we automatically merge existing report with current data, we may include outdated data from existing report.

**Comment by brendaHuang** [comment]
Looks great. Maybe we can move `fixedItemCount` to each summary, since each run has its own `fixedItemCount`.
