### ISSUE TITLE
Type Inference Selection Interactive Mode

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#744]
We talked about this a bunch, however I can't seem to find the ticket/issue. 

Essentially this is when Rehearsal can provide multiple options for type inference we should yield and prompt the user to select/accept/edit/discard the inferred type. This is similar functionality to what you find in VSCode.

**Comment by egorio** [comment]
@lynchbomb  @haochuan 

We have very few cases when code fixes provide few options for the same diagnostic. The only case that came to mind is "remove or underscore unused function param", but we currently decided not to modify the code and don't use those fixes.

We don't have cases when rehearsal provides few options for type inference because this happens for different errors/code positions. For instance "infer from usage" infer from jsdoc" happening in different places.

We might have those cases for type inference once in future, but we basically create fixes to cover cases when TS is useless (:any and :object).

I don't think we need to add this feature at this stage... and probably won't need to add in the future for type inference... or we can just create separate plugin to cover cases TS can't handle... but this is probably easy to do in IDE :)

**Comment by lynchbomb** [comment]
For posterity #544
