### ISSUE TITLE
RFC: CLI UX improvements

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#747]
In progress... thinking about providing a more flexible CLI to cover different behavior:

The idea of these changes in CLI UX is to provide users with a more flexible way to migrate apps the way they prefer.
Users can migrate simple apps at once or do it step by step running commands they need at the moment and creating more granular PRs.

### `rehearsal migrate`

- Should prompt with interactive mode.
- 

Trying to migrate an app running the next commands: `validate` -> `init --ts=stable` -> `fix` -> `report`
The command can ask the user to choose particular options for each step in interactive mode (like do you want to override or append configs if exists).

A command can use flags and options from steps, for instance:
running `migrate --ts=beta --append --include=*** --retry --output=***` will run `init --ts=beta --append`, `fix --retry --include=**` and `report --output`.

###  `rehearsal upgrade`

Trying to upgrade an app running the next commands: `validate` -> `init --ts=latestBeta --append` -> `fix` -> `report`

_Will we be upgrading configs during `upgrade` right?_ 

### `rehearsal validate`

...

### `rehearsal init`

Creates `tsconfig` and `eslintconfig` *if they are not present* + installs related deps 
If config file/files exist user can be asked to choose to `override` them , `append` strict options or just `skip` this step (see below)

- `--ts=***` - configure to specific ts version to use (`stable` for `migrate`, `latestBeta` for `upgrade`)
- `--config=ts,lint,glint,...` generate only specific config and install related deps
- `--override` - override existing configs with proposed
- `--append` (`--strictify`) - append missing options to existing configs to make them stricter 
- `--skip` - skip this step if files exist
- `--configPath` = path to config files (if different from --entry)
- `--dryrun ` - output the expected changes for each config without modifying files 
- `--userConfig` - path to rehearsal config with flags for config step

## rehearsal lint

Just a wrapper over the lint plugin to allow users to create separate PR with lint-related changes (formatting).

## `rehearsal graph`

- CLI command can write out a `.dot` format directed graph format to disk. Effectively serializing the `migration-strategy`
- Should help **advanced users** determine what files or sub-set of files will be migrated.
- 

## `rehearsal fix`

Complexity: Currently would have to be broken out from **migrate** command and task. This is all controlled by the migrate package and not decomposed in to simple tasks in the CLI.

Searches for files to be updated, displays list of files to be touched, renames **js** files to **ts**, and runs code fixes on all **ts** files

- `--entrypoint=***` - entry file or directory
- `--include=***` (glob?) - only files under this path will be renamed to `ts` and code fixes will be run on `ts` (other files under entry will be used in compiler)
  -  Currently globs don't work too well for dependency-cruiser. I think just paths is sufficient.
- `--exclude=<path>,` 
- `--dryrun` - show files to migrate without running code fixes
- `--userConfig` - path to rehearsal config with flags for fix step
- `--safeFixes` - configure the plugin to run 
- `--***other plugins options` -
- `--explain` - display user-friendly explaining options being added... this is very doubtable  

## `rehearsal report`

Generate reports of issues that need to be fixed manually (TODOs)
 
- `--include=***`
- `--exclude=***`
- `--format` - sonar, etc...
- `--output=***`

## common options:

-- `--verbose` (`--debug=level`) - show debug information (instead of asking to set DEBUG=***)

**Comment by wondersloth** [comment]
We've reorganized and group some commands into the following **subcommands** for each **command** (e.g. migrate or ugprade).

| Subcommand                       | Steps (output)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| ----------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Validate**                      | Check eslint config<br><br>Check ts-config<br><br>Does package.json exist<br><br>Check: Ensure .rehearsal is under version control                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| **Initialize**                    | yarn add all deps for typescripting, elsint, pretter (Currently [dependency-install.ts](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/dependency-install.ts))<br>[Create tsconfig.json](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/config-lint.ts)<br>[Create eslint config](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/config-ts.ts)<br>[Update package.json with build:tsc and lint:tsc commands](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/create-scripts.ts) |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| **Graph** Migrate Only           | Display files graph for current<br>include, exclude<br>Use Case, Adjust input to be –entrypoint file or dir<br>OR<br>exclude a directory from package graph.<br><br>Prerequisites:<br>Deps installed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| **Migrate** Move | [Currently](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/convert.ts) [convert.ts](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/convert.ts)<br>Calls packages/migrate<br>Git mv all targeted .js files to .ts<br><br>This calls migrate via async import and passings listr context.                                                                                                                                                                                                                                                                                                    |
| **Migrate** or **Upgrade**: Lint                | Runs eslint with –fix                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| **Migrate** or **Upgrade**: Fix                 | Applies Code Fixes to .ts source                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| Report                        | Creates rehearsal todos for linting errors or ts-errors                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |


### Commands
**rehearsal migrate**
Sub-commands
```
Validate | Initialize | Graph | Migrate ( Move | Lint | Fix) | Report```
```

**rehearsal upgrade**
Sub-commands

```
Validate | Initialize | Upgrade ( Lint | Fix ) | Report
```

Example CLI output with sub-comamnds annotated


```
$ rehearsal migrate
info:    @rehearsal/migrate 1.0.7-beta
✔ [Validate] Validate project
✔ [Initialize] Install dependencies
✔ [Initialize] Create tsconfig.json
✔ [Initialize] Create eslint config
✔ [Initialize] Add package scripts
✔ [Migrate] Moving .js to .ts
    5 JS files converted to TS
✔ [Migrate] Lint all migrated .ts files and running –fix 
   5 linting errors have been fixed by rehearsal
✔ [Migrate] Fix applying all CodeFixes to .ts source
✔ [Report] Summary of migration and fixes
  11 errors caught by rehearsal
  4 have been fixed by rehearsal
  7 errors need to be fixed manually
  -- 7 ts errors, marked by @ts-expect-error @rehearsal TODO
  -- 0 eslint errors, with details in the report

```

**Comment by wondersloth** [comment]
### Simple and Advanced Usage of CLI
We should ensure backwards compatibility, meaning we need a one-step command and granular commands for advanced use cases.

**Simple**
```
$ rehearsal [migrate|upgrade]
```

Will run everything in one go, with all pre-and-post tasks

**Advanced**
To provide granular tasks for advanced use cases we could do:
```
$ rehearsal validate
$ rehearsal initialize
$ rehearsal graph
$ rehearsal migrate --skip-validate --skip-initialize --skip-graph --skip-report  OR --skip-all
$ rehearsal report
```

### rehearsal graph
Current issue if we break out rehearsal graph out to a command is that we need to:
- Serialize graph state to disk e(.g. `.rehearsal/migration-graph.json` https://graphviz.org/doc/info/lang.html )
- Rehydrate the graph or strategy with that state.

**Comment by lynchbomb** [comment]
@wondersloth @egorio 

We should focus first on landing all of the critical features for Ember-* work and improve type inference. Then we can talk about changing CLI UX; just because an early-adopter makes a suggestion, doesnt mean we need to implement it. A general rule of thumb should be keep the API as simple as possible. 

We can easily convert our internal CLI tasks into child commands which can be run atomically (kinda) since we do actually have pre-reqs. eg `migrate init --ts-only, --lint-only` etc. `migrate validate`, `migrate report`.

**Comment by egorio** [comment]
@wondersloth 

I would create 
```
$ rehearsal fix
```

additional to
```
$ rehearsal migrate --skip-validate --skip-initialize --skip-graph --skip-report
```

so, you can run migrate
```
$ rehearsal migrate --skip-fix
```

**Comment by egorio** [comment]
@lynchbomb 

> We should focus first on landing all of the critical features for Ember-* work and improving type inference.
