### ISSUE TITLE
Don't check for uncommitted files and create git commits by Rehearsal (by default)

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#754]
Rehearsal currently creates git commits at some steps.
This is not convenient for those users who want to review/modify files before committing them.
We can change Rehearsal behavior to 
- [ ] work without committing any files and just by ignoring any uncommitted changes.
- [ ] do not create any commits during its workflow (or create an option to create / not create commits)
- [ ] create more granular command to allow users to run only steps and get a small amount if they want to

**Comment by lynchbomb** [comment]
First pass lets just remove rehearsal commits. Based on UX if folks want an iterative commit / interactive mode we can expand and add this.

So this issue should be:

- remove rehearsal commits
- `warn` instead of `error` on dirty git
- create a new issue for a later milestone for more complex iterative / interactive commits
