### ISSUE TITLE
`rehearsal migrate` fails when no `node_modules` directory exits. 

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#760]
cli validate task, check if node_modules exists. 

Steps to reproduce:
- run `rehearsal migrate` on a repository that doesn't have a node_modules directory yet.
- Should warn or fail.

**Comment by haochuan** [comment]
I could not reproduce it from my side. The order of tasks would run as following:

- validate
- initialization
- installation
- ...

As far as I know, we don't need `node_modules` in validate and initialization, and during installation it would create `node_modules` dir since it runs `yarn/pnpm/npm` install.

@wondersloth What issue/error did you see specifically regarding this?

**Comment by wondersloth** [comment]
This may be a non issue now. Let me try in a repo.

**Comment by wondersloth** [comment]
Unable to reproduce this issue in any repos.
