### ISSUE TITLE
migrate init is still parsing/processing JS files

### ISSUE THREAD

**Issue by haochuan** [rehearsal-js/rehearsal-js#835]
During `rehearsal mgirate init`:

```
rehearsal migrate init
✔ Validate project
✖ Unexpected error when parsing <path-to-project-root>/src/foo.js....
◼ Install dependencies
◼ Create tsconfig.json
◼ Create eslint config
◼ Add package scripts
error:   Error: Unexpected error when parsing <path-to-project-root>/src/foo.js....
```

`migrate init` should not do anything about parsing and processing, seems like we didn't isolate the `init` subcommand in [initialize task](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/initialize.ts)

**Comment by chadhietala** [comment]
This all comes down to the fact that we are still running `discoverEmberPackages` and `getMigrationStrategy` in init. To fully decouple we need to remove roughly all of [this code](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/initialize.ts#L42-L141) in the init task out into its own task (maybe called `analyze`) that is only ran during `rehearsal migrate`. The caveats are:

1. The config-ts command [wants the list of files](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/tasks/config-ts.ts#L69) to add to `includes`. I think we should move this step of adding to the tsconfig into the new `analyze` task or its own task.
2. You will need to re-read the userConfig in the `analyze` task so the downstreams tasks have access to it

In addition to this I think we can:

1. Remove [all of these tasks](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate/index.ts#L136) except `validate` in `rehearsal migrate` since people should run `rehearsal migrate init` before.
2. We should change the code of `validate` to take a flag that allows us to validate different things based on when its used e.g. `validate(options, logger, 'init')`, `validate(options, logger, 'migrate')`, `validate(options, logger, 'regen')`. We would always want to check for tsconfig and eslint for 'migrate' and 'regen'
3. I think we can get rid of the `-u` flag and just check for pressence of `rehearsal-config.json`. We should log that we are doing this.

This [branch](https://github.com/rehearsal-js/rehearsal-js/compare/master...chietala/init) might prove as a good starting point.

**Comment by haochuan** [comment]
@chadhietala All of the stuff makes sense to me, except:

1. `-u` is already optional and default to `rehearsal-config.json`. I still want to keep the option to have a way to pass config file in different location and with different filename.
2. We cannot remove dep install, tsconfig, lint config, etc in default tasks, since we are just isolating the `init` command instead of removing it from `migrate`. Just running `rehearsal migrate` with `rehearsal migrate init` is still a valid process.
