### ISSUE TITLE
Enhancement: Rehearsal should refuse to run on a typescript project

### ISSUE THREAD

**Issue by brendaHuang-2023** [rehearsal-js/rehearsal-js#932]
Ideally Rehearsal should refuse to run on an existing typescript project. Now it runs, even though the project is on the latest typescript.

**Comment by egorio** [comment]
I think this is about rehealsal migrate.

**Comment by lynchbomb** [comment]
Since you can run an iterative migration / partial migration the existence of typescript dep or tsconfig.json isn’t sufficient to litmus if rehearsal migrate should run or not.

As such rehearsal will need to traverse the FS in question for .js files.

Additionally rehearsals regen command needs to run against partial migrated projects (ts/js)
